### ISSUE TITLE
Update docs to latest version

### ISSUE THREAD

**Issue by kassim** [what3words/w3w-android-wrapper#34]
https://developer.what3words.com/tutorial/android

The API docs advise use of version 3.1.11 which seems to have an annoying Guava dependency clash with the `com.google.guava:listenablefuture:1.0` dependency that a lot of popular Google/AndroidX libraries depend on.

I can confirm that your latest 3.1.21 doesn't have this issue but it wasn't immediately clear that a version update to your lib dependency would be the solution

**Comment by mani-w3w** [comment]
Hello @kassim, thanks for pointing out this missing update on our docs, we will release 3.1.22 this week and will update all documentation accordingly, will let you know when 3.1.22 is available.

Thank you,
Mani
